// Generated by CoffeeScript 1.10.0
(function() {
  var pev,
    slice = [].slice;

  pev = function() {
    var event;
    event = function() {
      var args, promise, subscriber;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      promise = new Promise(function(resolve) {
        return resolve(args);
      });
      return Promise.all((function() {
        var i, len, ref, results;
        ref = event.subscribers;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          subscriber = ref[i];
          results.push(subscriber(promise));
        }
        return results;
      })());
    };
    event.subscribers = [];
    event.add = function(callback) {
      event.subscribers.push(callback);
      return function() {
        return event.del(callback);
      };
    };
    event.del = function(callback) {
      var index;
      index = event.subscribers.indexOf(callback);
      if (index >= 0) {
        event.subscribers.splice(index, 1);
        return true;
      } else {
        return false;
      }
    };
    return event;
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = pev;
  }

  this.pev = pev;

}).call(this);
